<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="ClickHouse.Driver" Version="1.2.0" />
		<PackageReference Include="Gedaq.DbConnection" Version="10.0.0.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
		<PackageReference Include="NUnit" Version="4.5.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.12.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="10.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Testcontainers.ClickHouse" Version="4.11.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Gedaq\Gedaq.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="True" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Model\" />
		<Folder Include="TestOneTimeParts\" />
		<Folder Include="TestsParts\" />
	</ItemGroup>
</Project>
